apiVersion: apps/v1
kind: Deployment
metadata:
  name: retail-service
  namespace: default
  labels:
    tags.datadoghq.com/env: production
    tags.datadoghq.com/service: retail-service
    tags.datadoghq.com/version: "1.0"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: retail-service
  template:
    metadata:
      labels:
        app: retail-service
        tags.datadoghq.com/env: production
        tags.datadoghq.com/service: retail-service
        tags.datadoghq.com/version: "1.0"
        admission.datadoghq.com/enabled: "true"
      annotations:
        admission.datadoghq.com/java-lib.version: v1.47.3
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: retail-service
          image: docker.io/malikvti/retail-service:1.0
          env:
            - name: SPRING_REDIS_HOST
              value: "http://redis-16016.c74.us-east-1-4.ec2.redns.redis-cloud.com"
            - name: SPRING_REDIS_PORT
              value: "16016"
            - name: SPRING_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: redis-password
            - name: DD_PROFILING_ENABLED
              value: "true"
            - name: DD_LOGS_INJECTION
              value: "true"
            - name: DD_APPSEC_ENABLED
              value: "true"
            - name: DD_IAST_ENABLED
              value: "true"
            - name: DD_APPSEC_SCA_ENABLED
              value: "true"
            - name: DD_SERVICE_MAPPING
              value: "sqlserver:retail-db"
            - name: DD_SERVICE
              value: "retail-service"
