apiVersion: v1
kind: Secret
metadata:
  name: sqlserver-secret
  namespace: default
type: Opaque
data:
  username: c2E=       # base64 dari: sqluser
  password: UEBzc3cwcmQ=    # base64 dari: password
