apiVersion: v1
kind: Service
metadata:
  name: retail-service
  namespace: default
spec:
  type: ClusterIp
  selector:
    app: retail-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7070
