#apiVersion: apps/v1
#kind: ReplicaSet
#metadata:
#  name: retail-service
#spec:
#  replicas: 3
#  selector:
#    matchLabels:
#      app: retail-service
#  template:
#    metadata:
#      labels:
#        app: retail-service
#    spec:
#      containers:
#        - name: retail-service
#          image: docker.io/malikvti/retail-service:1.0
#          ports:
#            - containerPort: 7070

---

apiVersion: v1
kind: Service
metadata:
  name: retail-service
  namespace: default
spec:
  selector:
    app: retail-service
  ports:
    - protocol: TCP
      port: 7070
      targetPort: 7070

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: retail-service-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  labels:
    name: retail-service-ingress
spec:
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: retail-service
                port:
                  number: 7070
