apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: retail-service
spec:
  replicas: 3
  selector:
    matchLabels:
      name: retail-service
  template:
    metadata:
      name: retail-service
      labels:
        name: retail-service
    spec:
      containers:
        - name: retail-service
          image: docker.io/malikvti/retail-service:1.0
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: retail-service
  namespace: default
spec:
  selector:
    app: retail-service
  ports:
    - protocol: TCP
      port: 7070
      targetPort: 7070

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: retail-service-ingress
  labels:
    name: retail-service-ingress
spec:
  rules:
    - host: retail.service.com
      http:
        paths:
          - path: /
            backend:
              serviceName: retail-service
              servicePort: 80